### ISSUE TITLE
Links for alleles to MGI is using the wrong root URL

### ISSUE THREAD

**Issue by dmkrupke** [mgijax/mtb-wi#10]
Hey Andrew!

This is great! 

The link from the alleles to MGI is using the wrong root URL.

It is using: http://www.informatics.jax.org/reference/MGI:1856318
Should be: http://www.informatics.jax.org/allele/MGI:1856318

So nice to have the Citations on the facted page be something human-recognizable! :)

Debbie

**Comment by ahcurrier** [comment]
This is now resolved with the new mtbdao.jar provided by @sneuhaus .
