### ISSUE TITLE
Additional Information column on the Strain Summary page is only showing references

### ISSUE THREAD

**Issue by dmkrupke** [mgijax/mtb-wi#11]
The Additional Information column on the Strain page should be showing the same types of data as the Additional Information column on the Faceted Search page. The Strain page is missing several of these types of data.

See this faceted set: http://bhmtbdb01:8080/mtbwi2/facetedSearch.do#fq=pathologyImages%253A%255B*%2520TO%2520*%255D&fq=cytoImages%253A%255B*%2520TO%2520*%255D&fq=geneExpression%253Atrue

6 records have pathology images, cytogenetics images, and gene expression data.
1 of these 6 also has metastasis info.
The 6 are all from the 2 strains.
http://bhmtbdb01:8080/mtbwi2/strainDetails.do?key=8241
http://bhmtbdb01:8080/mtbwi2/strainDetails.do?key=8242

The Additional Information column on those strain pages is missing the metastasis, pathology, cytogenetics images, and gene expression information.

If we are only going to be showing references in that column and none of the other additional information then we should change the column header to reflect that.

**Comment by ahcurrier** [comment]
Hi @sneuhaus — Could you modify this to expose metastatis and other details?:
https://github.com/mgijax/mtb-dao/blob/4bbcfed9f2f643b514d39c2f0db44d9654e360ec/src/org/jax/mgi/mtb/dao/custom/mtb/MTBStrainTumorSummaryDTO.java#L26
Thanks. –A

**Comment by sneuhaus** [comment]
@ahcurrier  It has getMetastasizesToDisplay and getImageCount ( which are pathology images). It doesn't have any counts for cytogenetic images. I will look into adding those

**Comment by ahcurrier** [comment]
Thanks, @sneuhaus . I've added metastasis and pathology image info.

**Comment by sneuhaus** [comment]
@ahcurrier @dmkrupke I  need to add a calculation for cytogenetics images to the strain data model

**Comment by sneuhaus** [comment]
I have an updated mtb-dao.jar file to provide count for cytogenetic images

**Comment by ahcurrier** [comment]
Thanks, @sneuhaus . Is this something I can pull from a branch or is it easier for you to email?

**Comment by sneuhaus** [comment]
@ahcurrier Email on the way.
