### ISSUE TITLE
Model Details page Expand/Collapse not working for metastasis

### ISSUE THREAD

**Issue by dmkrupke** [mgijax/mtb-wi#12]
http://bhmtbdb01:8080/mtbwi2/tumorSummary.do?strainKey=7677&organOfOriginKey=17&tumorFrequencyKeys=66273,66278,66281,66276,66277,66275,66280,66274,66279

"Expand All" and "Collapse All" are working for "Tumor Genetics", "Tumor Cytogenetics", and "Pathology" but not for "Metastasis".

**Comment by ahcurrier** [comment]
Resolved here:
https://github.com/ahcurrier/mtb-wi/commit/b2563fb0c1abd472d1c759ad17b0729c14480d10
