### ISSUE TITLE
Frequency Facet does not return consistent results

### ISSUE THREAD

**Issue by DABegley** [mgijax/mtb-wi#13]
When I use the frequency facet for lung adenocarcinomas the results are interesting. If I choose >50%, I only get models that have only frequencies above 50%. I do not get any results were there are a range of frequencies including ones above 50% if there is a frequency below or equal to 50%. When I use < or equal to 50%, I get any result where there is a frequency below or equal to 50% even if there are results above 50%. When I use 0, I only get results where the only frequency is 0. If it is a range, 0-100 for example, that model is not listed. So a model that has a range of 50-68% is listed when I search for equal or <50% but not in >50%. I think the return pattern for >50% and equal to or <50% should be the same.

**Comment by ahcurrier** [comment]
This has been updated so the the <= 50% search applied to the max. The facet labels have been updated to make it clear what each choice does.

**Comment by DABegley** [comment]
The frequency facet sort is doing what Andrew says, “applies to Max”, but that now means that if the range has both below and above 50% values it only shows if you have no frequency sort chosen. Which might be what we want. That means a value of 0-100% is not listed on either sort. Also the =0 facet shows everything, even results with only 100%. So that is not right.
