### ISSUE TITLE
Carcinoma, carcinoma

### ISSUE THREAD

**Issue by DABegley** [mgijax/mtb-wi#15]
When you choose a tumor type you the get the option to refine the search with tumor subtypes but you can also choose frequencies that don’t have a subtype. When you do this the search shows the same word twice as tumor type; carcinoma, carcinoma as an example. Is there any better way to represent this like; carcinoma-no subtype?

**Comment by ahcurrier** [comment]
I think is needs to be handled in Solr. @sneuhaus — possible to name subtype fields to be different from the parent?

**Comment by sneuhaus** [comment]
@DABegley @ahcurrier  I will update the solr index after hours tonight.

**Comment by dmkrupke** [comment]
I just saw the result of this change on the Faceted results. I hate to be Debbie downer, so to speak, but IMO it looks awful. :( The vast majority of our records have no subtype and are the parental, root type. Adding the "no subtype" text to thousands of records looks super messy to me. I would much rather the facet choices look a little funky, than to have most of our models look odd. We have been trying to find ways to visually simply things and this change is the exact opposite of that IMO.

**Comment by dmkrupke** [comment]
Of the 105,600 TF records in the database 87,338 (82.7%) have no hyphen in the tumor classification.

Also adding "no subtype" to all the parental types implies that subtypes exist and for many of the terms in our vocabulary that isn't the case.

**Comment by DABegley** [comment]
That actually is a good point. While all tumors likely have sub-types we do not have them listed in the database so it could get peole to think we do have them listed. The best solution would be to somehow just not duplicate the term in the display.

**Comment by dmkrupke** [comment]
In our current tumor classification vocabulary we have 233 parental terms. 67% of those parental terms currently have zero subtypes in the vocabulary.

**Comment by dmkrupke** [comment]
Besides looking awful in the Faceted Results, adding that extra text puts the Faceted Results out of sync with the Model Details page data. Please remove the "no subtype" text. Pretty please?!

**Comment by sneuhaus** [comment]
@dmkrupke  I will update the Solr index after hours to remove the "-subtype"
