### ISSUE TITLE
About Us page needs updating

### ISSUE THREAD

**Issue by CarolBult** [mgijax/mtb-wi#17]
The link to the About Us page needs to be updated.[http://bhmtbdb01:8080/mtbwi2/about-us.jsp](url)

The page title is Database Summary. Should be "About Us"
The content of the page needs updating.
There should be information on that page for how to cite the resource (just a link to the how to cite us page is sufficient)

**Comment by ahcurrier** [comment]
Title and CSS updated here:
https://github.com/ahcurrier/mtb-wi/commit/841cfff75c0ab99a238d4ec5410c8ae64384cb34

Content still needs to be updated. @CarolBult — who should handle the content update?
Thanks. –A

**Comment by CarolBult** [comment]
I sent draft text to the team last week.

**Comment by CarolBult** [comment]
[MMHCDB_Changes.pptx](https://github.com/mgijax/mtb-wi/files/4912786/MMHCDB_Changes.pptx)

**Comment by DABegley** [comment]
Here are my text comment.

To ensure maximum data accessibility and compatibility we follow strict adherence to community nomenclature standards, ontologies, and minimal information standards

**Comment by CarolBult** [comment]
@ahcurrier  Power point slides illustrate the content for the About Us page.

[MMHCDB_AboutUs.pptx](https://github.com/mgijax/mtb-wi/files/4920536/MMHCDB_AboutUs.pptx)

**Comment by DABegley** [comment]
Looks good except the numbers for PDX and images do not have commas and the numbers for models, frequencies and references do.
