### ISSUE TITLE
Antibody Staining Report

### ISSUE THREAD

**Issue by CarolBult** [mgijax/mtb-wi#18]
Other Resources-> Antibody Staining Report

There is nothing on the page other than links to a spreadsheet. This resource needs a Read Me file or something to let people know what it is about.

**Comment by DABegley** [comment]
I'll put one together.

**Comment by DABegley** [comment]
Herer is a blurb for the top of the page.

Immunological staining is a powerful tool in studying biology. Antibodies used to study these stainings have different species specificity and optimal conditions. Knowing these details allows a researcher to choose the best antibody for their purposes. The MMHCdb Immunohistochemistry page contains a detailed list of antibodies that have been tested in mice by researchers. The page contains antibody details and links to provider and antibody pages, conditions the antibody has been tested under and results of testing. Negative results are included.

**Comment by ahcurrier** [comment]
Updated here:
https://github.com/mgijax/mtb-wi/commit/15bf1f47c336ff185114d8f717e513d584d38d0d

**Comment by ahcurrier** [comment]
Hi @CarolBult — please let know if the above copy is approved and I will close this issue.

**Comment by CarolBult** [comment]
Here is the text...just need to hear from @DABegley about acknowledgements for the individuals that provided the data.

Antibodies used for immunohistochemistry (IHC) vary in species specificity and optimal assay conditions.  The MMHCdb Immunohistochemistry page summarizes information for antibodies that have been tested on mouse tissues, including antibody providers, conditions used to test antibody staining, and results of the testing. Negative results are included.

**Comment by DABegley** [comment]
Antibody information data sets have been submitted by John Sundberg and Lesley Bechtel from the Jackson Laboratory, Peter Vogel from St. Jude and Robert Coffey and Kelli Boyd from Vanderbilt.

**Comment by CarolBult** [comment]
Final text:

Antibodies used for immunohistochemistry (IHC) vary in species specificity and optimal assay conditions. The MMHCdb Immunohistochemistry page summarizes information for antibodies that have been tested on mouse tissues, including antibody providers, conditions used to test antibody staining, and results of the testing. Negative results are included.

The data in this report were submitted by Dr. John Sundberg and Lesley Bechtel (The Jackson Laboratory), Dr. Peter Vogel (St. Jude), and Drs. Robert Coffey and Kelli Boyd (Vanderbilt).

**Comment by ahcurrier** [comment]
Thanks @CarolBult  and @DABegley . Now updated.
