### ISSUE TITLE
Lymphoma Pathology Report Needs More Information

### ISSUE THREAD

**Issue by CarolBult** [mgijax/mtb-wi#19]
Other Resources -> Lymphoma Pathology Report [http://bhmtbdb01:8080/mtbwi2/lymphoma.jsp](url)

There is nothing on this page to give people any idea what this report is. There are only links to excel sheets. It needs some kind of context for the users.

**Comment by DABegley** [comment]
I'll write a blurb up for this too.

**Comment by DABegley** [comment]
Here is a proposed blurb.

Identification of different types of lymphomas and leukemia’s is a complex task involving pathological examination and histological and immunological staining. Different markers are expressed at different levels in different tumors and help define a tumor type. The MMHCdb Lymphoma pathology page contains a list of different lymphomas/leukemia’s stained for different markers, the tissue and staining level, background strain and Case #s. The Case # is a link to a web page containing detailed information on staining pattern and level of a specific marker in that tumor, pathological notes on characteristic of that tumor that help identify specific type, a link to a whole-slide scanned image and probe information. This information was submitted by Jerrold Ward and is from a 2001 NIH study set.

**Comment by ahcurrier** [comment]
Resolved here:
https://github.com/mgijax/mtb-wi/commit/c3916e0c1e12f367e25c38066d52eaf973c9dc7e

**Comment by ahcurrier** [comment]
Hi @CarolBult — please let know if the above copy is approved and I will close this issue.

**Comment by CarolBult** [comment]
The only thing that needs to be added is if the data are for mouse or human or both. It is not clear from the text.

**Comment by DABegley** [comment]
The data we have posted is for mouse. Jerry has lots of human data he is interested in us posting but all the data we are currently showing is for mouse. We could add mouse here to make that clearer, "The MMHCdb Lymphoma pathology page contains a list of different mouse lymphomas/leukemia’s stained for different markers, the tissue and staining level, background strain and Case #s..\"

**Comment by CarolBult** [comment]
Final Text:

Identification of different types of lymphomas and leukemia’s is a complex task involving assessment of pathology, histology, and immunology. Different markers are expressed at different levels in different tumors and help define a tumor type. The MMHCdb Lymphoma pathology page contains details about markers used to characterize lymphomas/leukemia’s in mouse models. The examples are linked by Case # to whole slide images that illustrate staining patterns and levels of a specific markers for a particular tumor type.  The information in this report was submitted by Dr. Jerrold Ward from a 2001 NIH study set.

**Comment by ahcurrier** [comment]
Thanks @CarolBult and @DABegley . Now updated.
