### ISSUE TITLE
PDX Search and PDX Like Me links do not work either

### ISSUE THREAD

**Issue by DABegley** [mgijax/mtb-wi#21]
PDX search link give sme a blank blue page. PDX Like Me gives a 500 error.

**Comment by ahcurrier** [comment]
This may be caused by master code for PDX needing to be merged into the dev branch. @sneuhaus — how would you like to handle this merge?

**Comment by ahcurrier** [comment]
Merge is now done and these work. I'm updating the CSS for the PDX Like Me page to work with the new header and footer.
