### ISSUE TITLE
Advanced Search name covered up

### ISSUE THREAD

**Issue by DABegley** [mgijax/mtb-wi#22]
I just noticed that the facet menu covers up the name for the advanced search page in the upper left corner. As you scroll the page up and down te name appears once but is usually covered up. Looks a bit off.

**Comment by dmkrupke** [comment]
I was just going to open an issue for this. It is happening on the Mac as well, Safari, Firefox, and Chrome.

**Comment by DABegley** [comment]
I tested Chrome and Firefox. I just tested it on IE and nothing works. The page does not reneder at all, I will open a new issue.

**Comment by ahcurrier** [comment]
Title issue is resolved here:
https://github.com/ahcurrier/mtb-wi/commit/78ce3fa34b3d490673ea9b74b8f8f0fbc0cdfd8b
