### ISSUE TITLE
Update tumor frequency grid

### ISSUE THREAD

**Issue by ahcurrier** [mgijax/mtb-wi#25]

**Comment by CarolBult** [comment]
I'm seeing that the tumor frequency grid lacks grid lines....is resolving that part of this ticket?

**Comment by ahcurrier** [comment]
Hi @CarolBult — Yes, that is part of this ticket.

**Comment by ahcurrier** [comment]
Ready for review. E.g.:
http://bhmtbdb01:8080/mtbwi2/dynamicGrid.do

**Comment by ahcurrier** [comment]
Notes:
+ All tool tips point to tumorsearchresults which doesn't exist in new design.

**Comment by sneuhaus** [comment]
It looks like we removed the page that the grid cells link to.
I think I can update the solr index so we can link to the advanced search.

**Comment by CarolBult** [comment]
@ahcurrier 
There is some munged text on the You searched for....section of the results page when you click on a cell in the tumor frequency grid. See screenshots below. It shows the cell that I clicked in and the results.
<img width="498" alt="Screen Shot 2020-07-16 at 3 30 50 PM" src="https://user-images.githubusercontent.com/8211639/87714312-94d24580-c779-11ea-985c-318d9698e19f.png">
<img width="897" alt="Screen Shot 2020-07-16 at 3 30 36 PM" src="https://user-images.githubusercontent.com/8211639/87714318-969c0900-c779-11ea-9227-f5d86b0190c2.png">

**Comment by ahcurrier** [comment]
Now cleaned up.
