### ISSUE TITLE
Update PDX Like Me help

### ISSUE THREAD

**Issue by ahcurrier** [mgijax/mtb-wi#27]
Move from static html to jsp and use new template.

**Comment by ahcurrier** [comment]
Updated here:
https://github.com/mgijax/mtb-wi/commit/74e2175296f4af09b3104d9f3d5c782da7643821

**Comment by CarolBult** [comment]
I noticed on the PDX Like Me help there is no graphic to illustrate the graphical results.  Also, no link back to the PDX Like Me search form.

**Comment by ahcurrier** [comment]
Thanks @CarolBult . Is this something that the group should update and approve? Right now this page uses the existing content on the current page here: http://tumor.informatics.jax.org/mtbwi/live/www/html/PDXLikeMeHelp.html

**Comment by CarolBult** [comment]
The visualization functionality was added late in the game so there was never an illustration added. See attached.

<img width="1310" alt="Screen Shot 2020-07-13 at 1 16 11 PM" src="https://user-images.githubusercontent.com/8211639/87333425-16706c00-c50b-11ea-8f87-db5cd24ed3d2.png">

**Comment by ahcurrier** [comment]
Thanks @CarolBult . Now updated.
