### ISSUE TITLE
Update pdxLikeMeVis.jsp

### ISSUE THREAD

**Issue by ahcurrier** [mgijax/mtb-wi#38]

**Comment by ahcurrier** [comment]
Ready for review:
http://bhmtbdb01:8080/mtbwi2/pdxLikeMe.do

**Comment by CarolBult** [comment]
@ahcurrier 
This looks good...just move the explanatory text for the visualization tool to before the graphic so that the organization is similar to the explanation of the tabular view...i.e., text first, then graphic.

**Comment by dmkrupke** [comment]
After you click on "Visualize" on the above page the resulting table has a horizontal scroll bar that is obscuring the text in the box directly above it. Maybe if the column is wider then the scroll bar would not show up?
<img width="98" alt="Screen Shot 2020-07-16 at 9 14 12 AM" src="https://user-images.githubusercontent.com/25062971/87675057-e44a4e80-c744-11ea-8a10-b16ae05659fc.png">

**Comment by ahcurrier** [comment]
@dmkrupke  — What browser, OS, and device are you using? Do you see the same behavior on the current site?

**Comment by dmkrupke** [comment]
MacOS Mojave. The screenshot below is, left to right, Chrome, Firefox, & Safari. (Safari now is fixed. The other 2 are still showing an overlap.)
<img width="588" alt="Screen Shot 2020-07-16 at 9 41 47 AM" src="https://user-images.githubusercontent.com/25062971/87678267-bbc45380-c748-11ea-8d98-e9ad7bc354f8.png">

I'll try clearing the cache on each of them.

**Comment by dmkrupke** [comment]
The device is a MacBook Pro.

**Comment by dmkrupke** [comment]
Cleared the cache and reloaded all 3. 

Chrome (Version 84.0.4147.89 (Official Build) (64-bit)) and Firefox (.9.0esr (64-bit)) still overlapping as shown above. 

Safari (Version 12.1.2 (14607.3.9)) not overlapping.

**Comment by dmkrupke** [comment]
Just updated Firefox to 68.10.0esr (64-bit), and now the display is not overlapping.

<img width="106" alt="Screen Shot 2020-07-16 at 10 46 27 AM" src="https://user-images.githubusercontent.com/25062971/87685683-abfd3d00-c751-11ea-9d59-3d9e8f09628e.png">

I will go see if Chrome has an update available.

**Comment by dmkrupke** [comment]
Google Chrome reports that it is up to date (Version 84.0.4147.89 (Official Build) (64-bit)).
It is still showing the overlap due to the scroll bar.
<img width="103" alt="Screen Shot 2020-07-16 at 10 49 21 AM" src="https://user-images.githubusercontent.com/25062971/87686063-144c1e80-c752-11ea-8931-56b7536cf67f.png">

**Comment by dmkrupke** [comment]
Investigating a bit more. The scroll bar seems to disappear (Chrome and Firefox) or shift to the entire graph (Safari) when I narrow the window after the page loads. 

If I make the window extra wide so that the font size of the column headers increases I get some funky display issues for the mutations (in all 3 browsers).

<img width="624" alt="Screen Shot 2020-07-16 at 11 31 59 AM" src="https://user-images.githubusercontent.com/25062971/87690962-0e593c00-c758-11ea-9ca9-d8db6032eae2.png">

(left to right: Chrome, Firefox, Safari)

**Comment by ahcurrier** [comment]
@dmkrupke — Does this issue exist on the current site as well?

**Comment by dmkrupke** [comment]
On the current web site the visualization page looks like this initially (Chrome, Firefox, Safari) after clicking the button.
<img width="1167" alt="Screen Shot 2020-07-16 at 2 37 42 PM" src="https://user-images.githubusercontent.com/25062971/87709372-2c339a80-c772-11ea-93c3-1649762c0e2e.png">

If I fiddle with the window width on the current web site Chrome & Firefox hold the scroll bar under the content. 
<img width="508" alt="Screen Shot 2020-07-16 at 2 40 56 PM" src="https://user-images.githubusercontent.com/25062971/87709513-63a24700-c772-11ea-8d85-844174989b8b.png">

Safari with the current web site splits the scroll bar and develops an overlap problem if I resize the window in some circumstances.
<img width="324" alt="Screen Shot 2020-07-16 at 2 41 35 PM" src="https://user-images.githubusercontent.com/25062971/87709606-846a9c80-c772-11ea-92a7-c2624ab3a682.png">

**Comment by ahcurrier** [comment]
@dmkrupke — I cannot reproduce this in any browser. What is the exact URL you are looking at?

**Comment by dmkrupke** [comment]
Weird!
I'm using this URL:
http://bhmtbdb01:8080/mtbwi2/pdxLikeMe.do

I'm leaving the example text in the search box and clicking on the "Visualize" button.

Maybe it is a MacOS Mojave thing?

**Comment by CarolBult** [comment]
I'm running Firefox on MacBookPro with Mojave. The text on the graphic is microscopic and I don't see a scroll bar.
<img width="863" alt="Screen Shot 2020-07-16 at 3 27 35 PM" src="https://user-images.githubusercontent.com/8211639/87713990-15447680-c779-11ea-930b-2553628862c9.png">

**Comment by dmkrupke** [comment]
Weird! Mine has the little scroll bar initially. I can get it to look like that (no scroll bar) if I resize the width of the window slightly. However if I make it too wide it goes all wonky with the rows not matching.

**Comment by dmkrupke** [comment]
I'm going to shut all my apps down and restart my computer.

**Comment by dmkrupke** [comment]
Restarted the computer. The odd behavior remains. I give up. I have no idea what is causing it. It's minor anyhow.

**Comment by ahcurrier** [comment]
OK to launch with this, then?

**Comment by dmkrupke** [comment]
I vote that it's ok. It is super minor, and, apparently, rather non-reproducible (from my computer to Carol's at least).

**Comment by ahcurrier** [comment]
Ok, I will close.
