### ISSUE TITLE
Update pdxRequestForm.jsp

### ISSUE THREAD

**Issue by ahcurrier** [mgijax/mtb-wi#41]

**Comment by ahcurrier** [comment]
Ready for review:
http://bhmtbdb01:8080/mtbwi2/pdxRequest.do

**Comment by CarolBult** [comment]
Just needs a small text change...
Change: "Fill out our brief web form and we will contact you in 1-2 business days."
to "Fill out the web form below and a Jackson Laboratory Technical Information Specialist will contact you in 1-2 business days."

**Comment by ahcurrier** [comment]
Updated.
