### ISSUE TITLE
Update pdxSearchResults.jsp

### ISSUE THREAD

**Issue by ahcurrier** [mgijax/mtb-wi#43]

**Comment by ahcurrier** [comment]
Ready for review. E.g.:
http://bhmtbdb01:8080/mtbwi2/pdxSearchResults.do

**Comment by CarolBult** [comment]
@ahcurrier 
The results box looks better but the top part of the for still needs to be adjusted. See slide #2 in the attached ppt slide deck.
[PDXSearch.pptx](https://github.com/mgijax/mtb-wi/files/4931419/PDXSearch.pptx)

**Comment by ahcurrier** [comment]
Updated to be more compact.
