### ISSUE TITLE
Update pathologyImageDetails.jsp

### ISSUE THREAD

**Issue by ahcurrier** [mgijax/mtb-wi#45]

**Comment by ahcurrier** [comment]
Ready for review. E.g.:
http://bhmtbdb01:8080/mtbwi2/pathologyImageDetails.do?key=930

**Comment by dmkrupke** [comment]
On the example page given above, the text beside Rod Bronson's name looks like code.

"Pathologist | Bronson RT ({pathology.pathologistAccId})"

That should display the J# just as the field above it does.

http://bhmtbdb01:8080/mtbwi2/referenceDetails.do?key=1238
J:94336

**Comment by dmkrupke** [comment]
The hyperlink from the bit of code is going to the correct page, just the label showing for the hyperlink should be changed to the J#. Thanks!

**Comment by ahcurrier** [comment]
Resolved
