### ISSUE TITLE
Link to funding info from footer is empty

### ISSUE THREAD

**Issue by CarolBult** [mgijax/mtb-wi#47]
Clicking on the "Funding" link in the footer goes to an empty page.

http://bhmtbdb01:8080/mtbwi2/funding.jsp

Text on that page should say:

MMHCDB is funded by [NCI R01 CA89713](https://projectreporter.nih.gov/project_info_description.cfm?aid=9916714&icde=50807165&ddparam=&ddvalue=&ddsub=&cr=1&csb=default&cs=ASC&pball=)

**Comment by ahcurrier** [comment]
Thanks @CarolBult . Now updated.
