### ISSUE TITLE
Strain names on Faceted Page not showing italics

### ISSUE THREAD

**Issue by dmkrupke** [mgijax/mtb-wi#5]
Hello,

I just started clicking around the beta site to start testing it, and I noticed that the strain names displayed on the faceted page do not match the strain names displayed on the Strain pages with regards to the italics.

Debbie

__________________

I haven't verified this, but my suspicion is the Solr data hasn't been reloaded since the italics for  the strain names were updated. The regular Solr data is updated every weekend but I have to do the new (mtbwi2) one manually.

Steve

**Comment by ahcurrier** [comment]
I believe this is now resolved by recent reload of Solr data. @sneuhaus , can you confirm?

**Comment by sneuhaus** [comment]
@ahcurrier @dmkrupke  I believe Debbie checked and this is resolved.
