### ISSUE TITLE
PDX description not needed at top of PDX Like Me page

### ISSUE THREAD

**Issue by CarolBult** [mgijax/mtb-wi#52]
http://bhmtbdb01:8080/mtbwi2/pdxLikeMe.do

The description of what PDX models are and the link to more information about the JAX PDX models should not be on the PDX Like me search page. Will need different text for that page.

**Comment by ahcurrier** [comment]
Thanks @CarolBult . I will remove. (This had been copied from the current PDX Like Me page.)
