### ISSUE TITLE
Changes to Help page

### ISSUE THREAD

**Issue by CarolBult** [mgijax/mtb-wi#53]
The layout and text on the Help page needs to be changed. Draft sent to the team July 7th.
[MMHCDB_Changes.pptx](https://github.com/mgijax/mtb-wi/files/4912784/MMHCDB_Changes.pptx)

**Comment by ahcurrier** [comment]
Thanks @CarolBult . I will hold off on updating until these changes are approved by the team.

**Comment by CarolBult** [comment]
Content for Help Page shown is attached power point

[MMHCDB_HELP_PAGE.pptx](https://github.com/mgijax/mtb-wi/files/4920453/MMHCDB_HELP_PAGE.pptx)

**Comment by CarolBult** [comment]
@ahcurrier the changes shown in the power point are final.
