### ISSUE TITLE
Hide normal / normal allele pairs from the Strain genetics sub table

### ISSUE THREAD

**Issue by dmkrupke** [mgijax/mtb-wi#54]
Alongside the issue that Dale noticed. I noticed that the normal/normal allele pairs are being displayed. We had discussed at some point in the past that those be hidden, but I think at this late date we will have to fix that after the rollout.

See the following for examples:
http://bhmtbdb01:8080/mtbwi2/strainDetails.do?key=8243
http://bhmtbdb01:8080/mtbwi2/strainDetails.do?key=143

**Comment by ahcurrier** [comment]
@dmkrupke - This should be resolved. Since the examples above have allele 1*2 symbols that are equivalent, the entire Strain Genetics row is now hidden. Is this correct?

**Comment by dmkrupke** [comment]
Yes, this is correct! Thank you! :)
