### ISSUE TITLE
Number of pathology images listed on Strain Summary doesn't match that on Model Details

### ISSUE THREAD

**Issue by dmkrupke** [mgijax/mtb-wi#55]
http://bhmtbdb01:8080/mtbwi2/strainDetails.do?key=143

Liver normal tissue (control)
24 pathology images listed on Strain Summary
12 on Model Details page (http://bhmtbdb01:8080/mtbwi2/tumorSummary.do?strainKey=143&organOfOriginKey=26&tumorFrequencyKeys=27663,27664,27728)

Lung adenoma
18 pathology images listed on Strain Summary
9 on Model Details page (http://bhmtbdb01:8080/mtbwi2/tumorSummary.do?strainKey=143&organOfOriginKey=4&tumorFrequencyKeys=8311,41761,46517,47966,47994,50144,50769,86695,86696,88533,101677,101722)

**Comment by dmkrupke** [comment]
Update... I looked at several of these and they are always an even number and always (thus far for the ones I've looked at) twice the value that they should be. Seems like maybe the images are being counted twice?

**Comment by ahcurrier** [comment]
@sneuhaus — Do you know why tumor.imageCount on strainSummary return 2x the images?

**Comment by sneuhaus** [comment]
@ahcurrier  Yes. I that should be fixed with the updated mtb-dao.jar I sent you today

**Comment by ahcurrier** [comment]
Thanks @sneuhaus — now resolved.
