### ISSUE TITLE
Treatment column has disappeared from the Strain Summary & Models not grouped properly

### ISSUE THREAD

**Issue by dmkrupke** [mgijax/mtb-wi#56]
http://bhmtbdb01:8080/mtbwi2/strainDetails.do?key=143

The Tumor Inducing Agent(s) column is missing from the Strain Summary. 

This is causing many models listed for the strain to appear redundant. The 3 rows for Lung adenoma are for spontaneous, BHT + urethane induced, and calorie restricted diet induced.

**Comment by dmkrupke** [comment]
Uh-oh. I think we have a bigger issue here. I was spot checking the references for the above lung adenoma models listed in the Strain Summary, and it appears that the models on the Strain Summary are being grouped by Treatment Type rather than Agent(s). Is this accurate? It should be by Agent(s).

**Comment by ahcurrier** [comment]
Hi @dmkrupke . I used your mockup here:
http://mgiprodwiki.jax.org/mediawiki/index.php/mtb:2018_Priorities:Simplify_UI#Strain_Summary
Is this mockup inaccurate? Thanks. –A

**Comment by dmkrupke** [comment]
Nope. The mock-up is accurate. That particular strain only has spontaneous tumor records so the column was not shown for that case. The first 2 examples in that section are strains with only spontaneous tumors. The last 3 strain examples have a mixture of spontaneous and induced tumors.

**Comment by dmkrupke** [comment]
There are also a variety of examples of sets of data for the strain pages where the Organ Affected column was required or not required depending on the data set for each strain.

**Comment by dmkrupke** [comment]
There is such a variety of data for different strains that I did several mock-ups for that page to show different particular representative cases (like needing the Organ Affected listed or needing multiple allele links to MGI). No one of them could show all the aspects that we required for the page. Same thing for the Model Details and Reference pages, there are multiple examples to show the different types of data sets that need to be represented.

**Comment by ahcurrier** [comment]
The simplest approach would be to always show a treatment column, even if it is empty. Otherwise, this means a rewrite of the controller code, since processing this in the view makes no sense. @sneuhaus - agree?

**Comment by ahcurrier** [comment]
In cases like this, am I expected to know this sort of thing?

**Comment by dmkrupke** [comment]
Always showing it is fine with me! It should be like the column in the Faceted Results.

**Comment by dmkrupke** [comment]
Sorry I wasn't clear about there being more than one example. My bad!

**Comment by ahcurrier** [comment]
Here:
http://bhmtbdb01:8080/mtbwi2/strainDetails.do?key=143
What is the default sort?

**Comment by dmkrupke** [comment]
Model name, please. Thanks!
