### ISSUE TITLE
Grouping of Models on the Strain Summary different from that on the Faceted Results

### ISSUE THREAD

**Issue by dmkrupke** [mgijax/mtb-wi#57]
There is an issue with the Strain Summary. I think it is possibly grouping tumor frequency records by treatment type instead of by the unique set of associated agents (as we have done on the Faceted Results page). I'll add screen shots for comparison.

The tumor frequencies are mammary gland adenocarcinomas for C3H/HeOuJ mice.

This is how the models look in the Faceted Results (8 mammary gland adenocarcinoma models for the strain):
<img width="1224" alt="Screen Shot 2020-07-14 at 5 10 45 PM" src="https://user-images.githubusercontent.com/25062971/87477128-9b37b480-c5f5-11ea-81ee-cf952aee8311.png">

This is how the same set of tumor frequencies looks on the C3H/HeOuJ Strain Summary screen (5 mammary gland adenocarcinoma models for the strain):
<img width="1442" alt="Screen Shot 2020-07-14 at 5 10 59 PM" src="https://user-images.githubusercontent.com/25062971/87477170-aee31b00-c5f5-11ea-82b1-cb1b39b46010.png">

The tumor frequencies are grouped differently. There are fewer of them. In cases where there is >1 agent the agent names are concatenated with no space or character between but a leading dot. The last model in the example is actually a metastatic lesion and should not be a row by itself on that table. It should be under the model that encompasses its parent record.

**Comment by dmkrupke** [comment]
The correct grouping is the one shown on the Faceted Results page.

**Comment by ahcurrier** [comment]
Agent rendering issue/dots is fixed

**Comment by ahcurrier** [comment]
For any issue like this, *it is crucial that you provide a URL*. Thanks.

**Comment by dmkrupke** [comment]
http://bhmtbdb01:8080/mtbwi2/strainDetails.do?key=62

**Comment by dmkrupke** [comment]
http://bhmtbdb01:8080/mtbwi2/facetedSearch.do#fq=organOriginParent%253A%2522Mammary%2520gland%2522&fq=strain%253A%2522C3H%252FHeOuJ%2522

**Comment by sneuhaus** [comment]
This is an issue with the data layer I'm working to resolve it.

**Comment by ahcurrier** [comment]
Hi @dmkrupke — Steve has updated the mtbdao.jar. Could you take a look and verify that this is now resolved? Thanks.

**Comment by dmkrupke** [comment]
The grouping of the models for the example strain is now correct! (http://bhmtbdb01:8080/mtbwi2/strainDetails.do?key=62)
However, none of the agent data is showing up in the Tumor Inducing Agent(s) column. Also the title should be changed from Treatment Agent(s) to Tumor Inducing Agent(s) to match that of the Faceted Results page). Thanks!

**Comment by sneuhaus** [comment]
Will find the missing agents

**Comment by ahcurrier** [comment]
Title changed. Data looks like it's there?

**Comment by sneuhaus** [comment]
I think the agents are still missing. I'm working on it.

**Comment by sneuhaus** [comment]
@ahcurrier  I sent you an updated mtb-dao.jar file to fix this

**Comment by dmkrupke** [comment]
The example page (http://bhmtbdb01:8080/mtbwi2/strainDetails.do?key=62) is currently showing Treatment Type(s) in the Tumor Inducing Agent(s) column rather than agent(s).

**Comment by dmkrupke** [comment]
For example, on the 5th row on the above page (http://bhmtbdb01:8080/mtbwi2/strainDetails.do?key=62) the data shown is "Diet, Hormone" when it should be "calorie restricted  •  pituitary isograft". Both the Treatment Types and the Agents are shown on the Model Details page (http://bhmtbdb01:8080/mtbwi2/tumorSummary.do?strainKey=62&organOfOriginKey=5&tumorFrequencyKeys=133)

**Comment by sneuhaus** [comment]
@dmkrupke @ahcurrier  I think the mtb-dao.jar file still needs to be replaced with the new one. I didn't sent it to Andrew until well after hours last night.

**Comment by sneuhaus** [comment]
@ahcurrier After a closer look it seems like the jar file has been updated but the strainDetailsCollapsed column and data have changed. I think a quick chat can sort this out.

**Comment by CarolBult** [comment]
@sneuhaus @ahcurrier 
I'm still seeing the problem that Debbie noted above
<img width="1017" alt="Screen Shot 2020-07-16 at 8 03 25 AM" src="https://user-images.githubusercontent.com/8211639/87669385-dd6b0e00-c73b-11ea-9fd1-acc45bb089fb.png">

**Comment by ahcurrier** [comment]
Resolved - agents now display.
