### ISSUE TITLE
Advanced Search freqeuncy facet behaviour 

### ISSUE THREAD

**Issue by sneuhaus** [mgijax/mtb-wi#59]
Dale: "The frequency facet sort is doing what Andrew says, “applies to Max”, but that now means that if the range has both below and above 50% values it only shows if you have no frequency sort chosen. Which might be what we want. That means a value of 0-100% is not listed on either sort. Also the =0 facet shows everything, even results with only 100%. So that is not right."

**Comment by ahcurrier** [comment]
Having no term selected means all frequency ranges are displayed. This is consistent with how the other facets behave.
Max = 0 now works as it should.
