### ISSUE TITLE
Remove "Other Database Links" from Strain Summary pages

### ISSUE THREAD

**Issue by dmkrupke** [mgijax/mtb-wi#6]
The old "Other Database Links" section has shown up on the new Strain Summary pages. We would like this section removed. Most of the links held in there are now no longer valid. Thanks!

**Comment by ahcurrier** [comment]
Hi @dmkrupke — Can you give me an example URL of where you are seeing this? Thanks. –A

**Comment by dmkrupke** [comment]
http://bhmtbdb01:8080/mtbwi2/strainDetails.do?key=62

**Comment by ahcurrier** [comment]
Thanks. Resolved here:
https://github.com/mgijax/mtb-wi/commit/1100bcb25cf9fefd40d72a3a73f4d44e256a6f3a
