### ISSUE TITLE
Update to 2020 facts & figures

### ISSUE THREAD

**Issue by sneuhaus** [mgijax/mtb-wi#67]

**Comment by dmkrupke** [comment]
Here is the URL for the ACS 2020 Facts & Figures:
https://www.cancer.org/content/dam/cancer-org/research/cancer-facts-and-statistics/annual-cancer-facts-and-figures/2020/cancer-facts-and-figures-2020.pdf

Also here is the updated summary of the Top 20. Prostate has passed Liver & bile duct to move into 6th place.

Cancer Site | 2020 ACS Est. Human Mortality Rank | No. of est. deaths USA 2020
______________________________________________________________________________________
Lung & other respiratory | 1 | 140,730
Lymphohematopoietic | 2 | 56,840
Colon & other intestine | 3 | 56,250
Pancreas | 4 | 47,050
Breast | 5 | 42,690
Prostate | 6 | 33,330
Liver & bile duct | 7 | 30,160
Brain & other nervous   system | 8 | 18,020
Urinary bladder | 9 | 17,980
Uterus and cervix | 10 | 16,880
Esophagus | 11 | 16,170
Kidney & renal pelvis | 12 | 14,830
Ovary | 13 | 13,940
Skin | 14 | 11,480
Stomach | 15 | 11,010
Oral cavity & pharynx | 16 | 10,750
Soft tissue (including heart) | 17 | 5,350
Gallbladder & other biliary | 18 | 4,090
Endocrine system | 19 | 3,260
Bones & joints | 20 | 1,720

**Comment by sneuhaus** [comment]
@dmkrupke this has been updated on the dev site

**Comment by dmkrupke** [comment]
Hey Steve! Sorry. Could you please direct me as to where I can view the Dev WI? I found a link to the Dev EI on the wiki but not the WI. @sneuhaus Thanks!

**Comment by sneuhaus** [comment]
Hi Debbie,

There currently isn’t a WI that points to the dev database that the dev EI uses.
I could with a little work change the mtbwi2 to use the same database as the dev EI.
It probably makes sense to have a devWI up and running since we have a devEI and dev database.


-Steve

**Comment by sneuhaus** [comment]
@dmkrupke 
By dev I meant the internal site on bhmtbdb01

**Comment by dmkrupke** [comment]
@sneuhaus Gotcha! Thanks!

**Comment by dmkrupke** [comment]
I checked it over on the dev WI. Looks good! Thank you!
