### ISSUE TITLE
Number of selections displayed at one time in some faceted search panels are too few and are wrapped

### ISSUE THREAD

**Issue by CarolBult** [mgijax/mtb-wi#69]
As I use the faceted search page I'm finding that that it is problematic to scroll through so many options on things like strain. And the wrapping make strain names even more confusing to sort through. 

We need a way to expand the faceted search panels so that the selectable entries are easier to navigate.

**Comment by ahcurrier** [comment]
Resolved here:
https://github.com/mgijax/mtb-wi/commit/d37095b27a80a6e747563403f10a3b5b2dfad9d2
