### ISSUE TITLE
Some strains are showing redundant allele info

### ISSUE THREAD

**Issue by dmkrupke** [mgijax/mtb-wi#7]
See the following for an example: http://bhmtbdb01:8080/mtbwi2/strainDetails.do?key=42

The strain / allele associations are showing up multiple times where the database has recorded the same association from different references.

**Comment by ahcurrier** [comment]
Hi @sneuhaus — It looks like strain.genetics is returning duplicates hence the above. Is this the intended behavior? Thanks. –A

**Comment by sneuhaus** [comment]
@ahcurrier  strain.consolidatedGenetics should resolve this

**Comment by ahcurrier** [comment]
Thanks, @sneuhaus . Resolved here:
https://github.com/mgijax/mtb-wi/commit/5de9b2629b0c2afd9f173f0097f88e890df345c9
