### ISSUE TITLE
Can't search for models by Diversity Outbred or Collaborative Cross

### ISSUE THREAD

**Issue by CarolBult** [mgijax/mtb-wi#70]
Can only search for J:DO mice by J:DO...and most people will not know this is the official name. Entering "Diversity" in the strain search box doesn't work.

**Comment by dmkrupke** [comment]
There is one strain currently marked in the database as being DO. The Diversity Outbred strain type is showing on the Strain Summary page (the capitalization is fixed on production currently, not yet on public), but it is not showing as a strain type in the facets on the Advanced Search page.

Strain Summary page: http://tumor.informatics.jax.org/mtbwi/strainDetails.do?key=9245
Advanced Search page: http://tumor.informatics.jax.org/mtbwi/facetedSearch.do
