### ISSUE TITLE
Faceted search results: more entries per page; ability to download results

### ISSUE THREAD

**Issue by CarolBult** [mgijax/mtb-wi#71]
If you ask for all outbred strains on the faceted search page you get 1900+ results 25 pages at a time. There is no way to ask for more rows to be displayed on a page and no option to download results.

**Comment by ahcurrier** [comment]
More entries per page:
https://github.com/mgijax/mtb-wi/commit/e96851dc430f5962e7836efb80b4e34d5e4c4cf7
