### ISSUE TITLE
Gene Expression Data text on Model Details page not linking out & not showing on Advanced Results

### ISSUE THREAD

**Issue by dmkrupke** [mgijax/mtb-wi#72]
This is a conundrum.
 
http://tumor.informatics.jax.org/mtbwi/tumorSummary.do?strainKey=9245&organOfOriginKey=140&tumorFrequencyKeys=106484,106487,106486,106485,106488
 
The above model page lists the text "Gene Expression Data". It appears to be hyperlinked (the hand appears when hovering over it) but attempting to click on it does nothing. It should be linking out to https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE89207
 
The tumor frequency involved is MTB-ID:106484. The GEO record is GSE89207. It has a long list of samples in our EI, all attached to that MTB-ID. (The other IDs listed in the URL are for metastases.)
 
The Gene Expression Data indication is missing from the Advanced Search Results page Additional Information column.
 
http://tumor.informatics.jax.org/mtbwi/facetedSearch.do#fq=metsTo%253A%2522Lung%2522&fq=strain%253A%2522(C57BL%252F6-Tg(TRAMP)8247Ng%252FJ%2520x%2520J%253ADO)F1%2522
 
I think this is only a visual omission as filtering by "Has Gene Expression Data Link(s)" leaves the model remaining in the search results. I tried filtering by only "Has Gene Expression Data Link(s)" and, as far as I can tell, none of the matching models has an indication of this in the Additional Information column.

**Comment by sneuhaus** [comment]
@dmkrupke This should be fixed on bhmtbdb01. The indication for Gene Expression data appears on the advanced search results and on the tumor summary page series are displayed with the appropriate link

**Comment by dmkrupke** [comment]
Thank you! That looks good! And I checked the link out to GEO, and it worked. Yay!

**Comment by sneuhaus** [comment]
I will update the public site today.
