### ISSUE TITLE
Font and spacing issues on the PDX Details pages

### ISSUE THREAD

**Issue by CarolBult** [mgijax/mtb-wi#73]
@ahcurrier @sneuhaus 
[PDX_Details_Layout.pptx](https://github.com/mgijax/mtb-wi/files/5080925/PDX_Details_Layout.pptx)

The PDX Details pages have readability issues. See attached Power Point slide deck for overall organization of this page as well as details for how each section should look and examples of the current issues. 

This is a high priority as it is one of the most accessed sections of MMHCdb.

**Comment by ahcurrier** [comment]
There are many different requests here. Could you please break this up into separate issues? Thanks.

**Comment by CarolBult** [comment]
@ahcurrier 

Yes. I can. Since they are all sort of inter-related I'm not sure how to break them up to make implementation as straightforward as possible but I'll do my best!

**Comment by ahcurrier** [comment]
Resolved
https://github.com/mgijax/mtb-wi/commit/4c2f0f26f7e6a3b09af517f2825c2ddc5432825b
