### ISSUE TITLE
"Tumors" on the Strain Summary and Reference Summary pages should be "Models"

### ISSUE THREAD

**Issue by dmkrupke** [mgijax/mtb-wi#8]
"Tumors
15 unique tumor types displayed. A tumor group is a set of tumors that share the same tumor name, organ(s) affected, and treatment type."

The header above should be changed from "Tumors" to "Models". Also "unique tumor types" should be changed to "unique models" and "tumor group" should also be changed to "model". The text "for a specific strain" should be added at the end.

Like this:
"Models
15 unique models displayed. A model is a set of tumors that share the same tumor name, organ(s) affected, and treatment type for a specific strain."

Also the "Tumors" header on the Reference Summary page should be changed to "Models".

Thanks!

**Comment by ahcurrier** [comment]
Resolved here:
https://github.com/ahcurrier/mtb-wi/commit/a66794d74810f070bdaf2c8d4f6a7143f4fd5e10
