### ISSUE TITLE
Large font header on Reference Summary should be Short Citation rather than Title

### ISSUE THREAD

**Issue by dmkrupke** [mgijax/mtb-wi#9]
I think rather than displaying the title of a reference in large font on the top of the Reference Summary page, it would be better if we used the Short Citation (as displayed in the Additional Information columns).

Thanks!

**Comment by ahcurrier** [comment]
Hi @sneuhaus , to complete the above request, could you please add a shortCitation field to this DTO?:
https://github.com/mgijax/mtb-dao/blob/a91f27fd905c91cf2fd8cec4d22c75f988a76bf9/src/org/jax/mgi/mtb/dao/custom/mtb/MTBReferenceDetailDTO.java

**Comment by ahcurrier** [comment]
Thanks, @sneuhaus . Now resolved here:
https://github.com/ahcurrier/mtb-wi/commit/2d0544c10a893ec963368eac618e51abfcbb5fb4

**Comment by dmkrupke** [comment]
This looks great!!! :D
